name: Scheduled eBay Scraper

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日 日本時間12:00 に実行（UTC 3:00）
  workflow_dispatch:  # 手動実行を可能にする

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run the script
        run: node scrapeEbay.js
